module.exports = {
    MODIFIER_PUBLIC:3,
    MODIFIER_PROTECTED:2,
    MODIFIER_PRIVATE:1,

    DECLARE_CLASS:1,
    DECLARE_INTERFACE:2,
    DECLARE_ENUM:3,

    DECLARE_PROPERTY_VAR:1,
    DECLARE_PROPERTY_CONST:2,
    DECLARE_PROPERTY_FUN:3,
    DECLARE_PROPERTY_ACCESSOR:4,
    DECLARE_PROPERTY_ENUM_KEY:5,
    DECLARE_PROPERTY_ENUM_VALUE:6,

    BUILD_OUTPUT_EVERY_FILE:1,
    BUILD_OUTPUT_MERGE_FILE:2,
    BUILD_OUTPUT_MEMORY_FILE:3,

    BUILD_ORIGIN_FILE:1,
    BUILD_ALL_FILE:2,

    BUILD_REFS_MODULE_ES6:1,
    BUILD_REFS_MODULE_COMMONJS:2,

    REFS_DECLARE_PRIVATE_NAME:'_private',
    REFS_DECLARE_PRIVATE_STATIC:'_privateStatic',

    BUILD_IMPORT_PATH_ABSOLUTE:1,
    BUILD_IMPORT_PATH_RELATIVE:2,
}